[package]
name = "minigrep"
version = "0.1.0"
authors = ["Namkai Fairfield <namkai.fairfield@gmail.com>"]
edition = "2018"
description = "My own implementation of grep"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
